version: '3.7'

services:

  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_DB: property_management
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
